### PR TITLE
Font lock improvements

### PR DESCRIPTION
**Pull request by dwa**
use keyword face rather than function name.

Also matches internal blocks, such as the connection block.

### CODE REVIEW

**Comment by syohex** [comment]
Could you show me sample file and its screenshot and add/update highlighting test ?

**Comment by dwa** [comment]
Absolutely.

I'm using the tao-theme (https://github.com/11111000000/tao-theme-emacs) in these screenshots. I also include a screenshot of some python code, for comparison.

after
before
python-comparison

Cheers!

**Comment by dwa** [comment]
And the sample file:

```
# modules/bastion/main.tf

resource "scaleway_server" "bastion" {
  name                = "bastion"
  image               = "${var.image}"
  type                = "${var.type}"
  dynamic_ip_required = true

  tags                = ["bastion"]

  security_group      = "${var.security_group}"

  connection {
    private_key  = "${file(var.ssh_private_key_path)}"
  }


  # setup a SOCKS server:
  provisioner "remote-exec" {
    inline = [
      "cat /etc/ssh/ssh_host_rsa_key.pub >> /root/.ssh/authorized_keys",
      "ssh -i /etc/ssh/ssh_host_rsa_key -f -N -D 0.0.0.0:1080 -o StrictHostKeyChecking=no -o CheckHostIP=no localhost",
      "pgrep -af '1080'"
    ]
  }
}
```

**Comment by syohex** [comment]
I don't think this change improves highlighting. However inner block highlighting is good and I have added special inner block highlighting at #17. Thanks for idea.

**Pull request closed without merging**
